rpc = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x046d17ca0b6856d4f1cc635b753b296d57b0a8382c492a9f55686ee6b314ba0e"

[indexing]
events_chunk_size = 1024
blocks_chunk_size = 1024
pending = true
polling_interval = 500
max_concurrent_tasks = 100
world_block = 1464035
contracts = []

[sql]
historical = []
