[package]
name = "orderbook"
version.workspace = true
edition.workspace = true

[dependencies]
dojo.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_token.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[lib]
